-- Olive Clean portable schema.
-- This is intentionally MariaDB/SQLite friendly: UUIDs are generated by the API,
-- and JSON values are stored as TEXT so the same local database works without a
-- separate database service. Hostinger can import this file into MariaDB.

CREATE TABLE IF NOT EXISTS app_users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  display_name VARCHAR(255),
  user_metadata TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_confirmed TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS user_roles (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  role VARCHAR(30) NOT NULL,
  UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS profiles (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL UNIQUE,
  display_name VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS booking_requests (
  id CHAR(36) PRIMARY KEY,
  service TEXT NOT NULL,
  home_type TEXT NOT NULL,
  bedrooms INT NOT NULL,
  bathrooms INT NOT NULL,
  frequency TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT,
  notes TEXT,
  referral_code TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clients (
  id CHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  neighborhood TEXT,
  preferences TEXT,
  notes TEXT,
  created_by CHAR(36),
  client_user_id CHAR(36),
  lat DECIMAL(10,7),
  lng DECIMAL(10,7),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
  id CHAR(36) PRIMARY KEY,
  client_id CHAR(36) NOT NULL,
  service TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'scheduled',
  scheduled_at DATETIME NOT NULL,
  completed_at DATETIME,
  assigned_to CHAR(36),
  duration_minutes INT,
  actual_duration_minutes INT,
  estimated_drive_minutes INT,
  price DECIMAL(12,2),
  notes TEXT,
  checklist_state TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS perks_members (
  id CHAR(36) PRIMARY KEY,
  client_id CHAR(36) NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  discount_percent INT NOT NULL DEFAULT 40,
  flexibility_zone TEXT,
  joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  program_type TEXT NOT NULL DEFAULT 'loyalty_club',
  cleanings_completed INT NOT NULL DEFAULT 0,
  free_cleanings_earned INT NOT NULL DEFAULT 0,
  free_cleanings_used INT NOT NULL DEFAULT 0,
  referral_code TEXT UNIQUE,
  referred_by CHAR(36)
);

CREATE TABLE IF NOT EXISTS feedback (
  id CHAR(36) PRIMARY KEY,
  job_id CHAR(36) NOT NULL,
  client_id CHAR(36) NOT NULL,
  rating INT NOT NULL,
  comments TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS perks_offers (
  id CHAR(36) PRIMARY KEY,
  perks_member_id CHAR(36) NOT NULL,
  cancelled_job_id CHAR(36) NOT NULL,
  offered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'offered',
  responded_at DATETIME,
  new_job_id CHAR(36)
);

CREATE TABLE IF NOT EXISTS employees (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  status TEXT NOT NULL DEFAULT 'onboarding',
  certifications TEXT,
  onboarding_checklist TEXT,
  photo_url TEXT,
  hired_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_performance (
  id CHAR(36) PRIMARY KEY,
  employee_id CHAR(36) NOT NULL,
  month DATE NOT NULL,
  jobs_completed INT DEFAULT 0,
  recleans INT DEFAULT 0,
  avg_rating DECIMAL(10,2) DEFAULT 0,
  avg_efficiency_pct DECIMAL(10,2) DEFAULT 0,
  attendance_score DECIMAL(10,2) DEFAULT 100,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (employee_id, month)
);

CREATE TABLE IF NOT EXISTS applicants (
  id CHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  resume_url TEXT,
  cover_note TEXT,
  status TEXT NOT NULL DEFAULT 'applied',
  applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  screening_score INT,
  years_experience INT,
  available_days TEXT,
  has_transportation TINYINT,
  job_posting_id CHAR(36),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lifecycle_events (
  id CHAR(36) PRIMARY KEY,
  client_id CHAR(36) NOT NULL,
  job_id CHAR(36),
  event_type TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT 'email',
  sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supply_items (
  id CHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'cleaning_supply',
  current_stock DECIMAL(12,2) NOT NULL DEFAULT 0,
  reorder_threshold DECIMAL(12,2) NOT NULL DEFAULT 5,
  unit TEXT NOT NULL DEFAULT 'units',
  last_restocked_at DATETIME,
  notes TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supply_usage_logs (
  id CHAR(36) PRIMARY KEY,
  supply_item_id CHAR(36) NOT NULL,
  employee_id CHAR(36),
  job_id CHAR(36),
  quantity_used DECIMAL(12,2) NOT NULL DEFAULT 1,
  logged_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_postings (
  id CHAR(36) PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL DEFAULT 'Nashville, TN',
  type TEXT NOT NULL DEFAULT 'full-time',
  requirements TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoices (
  id CHAR(36) PRIMARY KEY,
  client_id CHAR(36) NOT NULL,
  job_id CHAR(36),
  estimate_id CHAR(36),
  invoice_number TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  items TEXT NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_rate DECIMAL(10,4) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  due_date DATE,
  issued_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  paid_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS estimates (
  id CHAR(36) PRIMARY KEY,
  client_id CHAR(36) NOT NULL,
  estimate_number TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  items TEXT NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_rate DECIMAL(10,4) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  valid_until DATE,
  converted_invoice_id CHAR(36),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payslips (
  id CHAR(36) PRIMARY KEY,
  employee_id CHAR(36) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  hours_worked DECIMAL(12,2) NOT NULL DEFAULT 0,
  hourly_rate DECIMAL(12,2) NOT NULL DEFAULT 0,
  calculated_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  custom_amount DECIMAL(12,2),
  deductions TEXT,
  additions TEXT,
  net_pay DECIMAL(12,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft',
  notes TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenses (
  id CHAR(36) PRIMARY KEY,
  employee_id CHAR(36) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  category TEXT NOT NULL DEFAULT 'other',
  description TEXT NOT NULL,
  receipt_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME,
  reviewed_by CHAR(36),
  notes TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_availability (
  id CHAR(36) PRIMARY KEY,
  employee_id CHAR(36) NOT NULL,
  day_of_week INT NOT NULL,
  start_time TEXT NOT NULL DEFAULT '08:00',
  end_time TEXT NOT NULL DEFAULT '17:00',
  is_available TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (employee_id, day_of_week)
);

CREATE TABLE IF NOT EXISTS time_off_requests (
  id CHAR(36) PRIMARY KEY,
  employee_id CHAR(36) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  reviewed_by CHAR(36),
  reviewed_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_attachments (
  id CHAR(36) PRIMARY KEY,
  job_id CHAR(36) NOT NULL,
  uploader_id CHAR(36) NOT NULL,
  uploader_role TEXT NOT NULL DEFAULT 'staff',
  file_path TEXT NOT NULL,
  bucket TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loyalty_programs (
  id CHAR(36) PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  discount_percent INT NOT NULL DEFAULT 0,
  description TEXT,
  benefits TEXT NOT NULL,
  is_active TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loyalty_milestones (
  id CHAR(36) PRIMARY KEY,
  member_id CHAR(36) NOT NULL,
  milestone_type TEXT NOT NULL,
  triggered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  redeemed TINYINT NOT NULL DEFAULT 0,
  job_id CHAR(36),
  notes TEXT
);

CREATE TABLE IF NOT EXISTS team_messages (
  id CHAR(36) PRIMARY KEY,
  author_id CHAR(36) NOT NULL,
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supply_requests (
  id CHAR(36) PRIMARY KEY,
  employee_id CHAR(36) NOT NULL,
  supply_item_id CHAR(36) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'pending',
  notes TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shift_trade_requests (
  id CHAR(36) PRIMARY KEY,
  requester_id CHAR(36) NOT NULL,
  requester_job_id CHAR(36) NOT NULL,
  target_id CHAR(36),
  target_job_id CHAR(36),
  status TEXT NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  metadata TEXT,
  read TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_templates (
  id CHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  show_on_portal TINYINT NOT NULL DEFAULT 0,
  checklist_items TEXT NOT NULL,
  default_duration_minutes INT,
  default_price DECIMAL(12,2),
  is_active TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
  id CHAR(36) PRIMARY KEY,
  name TEXT,
  email TEXT,
  phone TEXT,
  location TEXT,
  bedrooms INT,
  bathrooms INT,
  frequency TEXT,
  urgency TEXT,
  score INT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'new',
  source TEXT NOT NULL DEFAULT 'chatbot',
  chat_transcript TEXT,
  notes TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  converted_job_id CHAR(36)
);

CREATE TABLE IF NOT EXISTS time_logs (
  id CHAR(36) PRIMARY KEY,
  employee_id CHAR(36) NOT NULL,
  job_id CHAR(36),
  clock_in DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  clock_in_lat DECIMAL(10,7),
  clock_in_lng DECIMAL(10,7),
  clock_out DATETIME,
  clock_out_lat DECIMAL(10,7),
  clock_out_lng DECIMAL(10,7)
);

CREATE TABLE IF NOT EXISTS perk_catalog (
  id CHAR(36) PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  description TEXT,
  perk_type TEXT NOT NULL DEFAULT 'discount',
  value_type TEXT NOT NULL DEFAULT 'percent',
  value DECIMAL(12,2),
  icon TEXT,
  color TEXT,
  is_active TINYINT NOT NULL DEFAULT 1,
  is_assignable TINYINT NOT NULL DEFAULT 1,
  max_uses INT,
  times_assigned INT NOT NULL DEFAULT 0,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS member_perks (
  id CHAR(36) PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  perks_member_id CHAR(36) NOT NULL,
  perk_catalog_id CHAR(36) NOT NULL,
  assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  assigned_by CHAR(36),
  status TEXT NOT NULL DEFAULT 'active',
  redeemed_at DATETIME,
  expires_at DATETIME,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS email_send_log (
  id CHAR(36) PRIMARY KEY,
  message_id TEXT,
  template_name TEXT NOT NULL,
  recipient_email TEXT NOT NULL,
  status TEXT NOT NULL,
  error_message TEXT,
  metadata TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_send_state (
  id INT PRIMARY KEY,
  retry_after_until DATETIME,
  batch_size INT NOT NULL DEFAULT 10,
  send_delay_ms INT NOT NULL DEFAULT 200,
  auth_email_ttl_minutes INT NOT NULL DEFAULT 15,
  transactional_email_ttl_minutes INT NOT NULL DEFAULT 60,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suppressed_emails (
  id CHAR(36) PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  reason TEXT NOT NULL,
  metadata TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_unsubscribe_tokens (
  id CHAR(36) PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  used_at DATETIME
);

CREATE INDEX IF NOT EXISTS idx_jobs_client ON jobs(client_id);
CREATE INDEX IF NOT EXISTS idx_jobs_schedule ON jobs(scheduled_at);
CREATE INDEX IF NOT EXISTS idx_jobs_assigned ON jobs(assigned_to);
CREATE INDEX IF NOT EXISTS idx_clients_user ON clients(client_user_id);
CREATE INDEX IF NOT EXISTS idx_employees_user ON employees(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, read, created_at);
CREATE INDEX IF NOT EXISTS idx_time_logs_employee ON time_logs(employee_id, clock_in);
